# Generated by Django 4.1.2 on 2022-10-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_payment_title_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
